/**
 * redux的命名
 * Created by gaoju on 2017/11/15.
 */
// 用户
export const USER_INFO = 'USER_INFO';
export const USERBASICINFO_UPDATA = 'USERBASICINFO_UPDATA';
export const USERBASICINFO_CLEAN = 'USERBASICINFO_CLEAN';
export const USERCOLLECTINFO_UPDATA = 'USERCOLLECTINFO_UPDATA';
export const USERCOLLECTINFO_CLEAN = 'USERCOLLECTINFO_CLEAN'
//首页
export const HOMESHOW_LIST_UPDATA = 'HOMESHOW_LIST_UPDATA';
export const HOMESHOW_LIST_CLEAN = 'HOMESHOW_LIST_CLEAN';
//page
export const PAGE_UPDATE_CURRENT = 'PAGE_UPDATE_CURRENT';
export const PAGE_CLEAN_CURRENT = 'PAGE_CLEAN_CURRENT';
//网络请求
export const REQUEST_LOADING = 'REQUEST_LOADING';
export  const REQUEST_DONE = 'REQUEST_DONE';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_CLEAN = 'REQUEST_CLEAN';

//math
export const ALLQUESTIONSLIST_UPDATE = 'ALLQUESTIONSLIST_UPDATE';
export const ALLQUESTIONSLIST_CLEAN =  'ALLQUESTIONSLIST_CLEAN';
export const QUESTIONSLIST_UPDATE = 'QUESTIONSLIST_UPDATE';
export const ALLEXAMLIST_UPDATE = 'ALLEXAMLIST_UPDATE';
export const EXAMLIST_UPDATE = 'EXAMLIST_UPDATE';
export const GETMAINQUESTION_UPDATA = 'GETMAINQUESTION_UPDATA';
export const GETFIRSTDATAOFPAPER = 'GETFIRSTDATAOFPAPER';
export const SECONDTESTQUESTIONS_UPDATA = 'SECONDTESTQUESTIONS_UPDATA';
export const GETCONTENTOFCHILDQUES_UPDATA = 'GETCONTENTOFCHILDQUES_UPDATA';
//定时
export const SET_TIMING = 'SET_TIMING';
export const CLEAR_TIMING = 'CLEAR_TIMING';